version: "3.3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    image: mysql:8.0
    volumes:
      - /docker/mysql/db_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_ROOT_PASSWORD: bar

  app:
    image: aomgroup/cli-base:base-7.3.11-build-0.0.1
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - redis
      - db
    volumes:
      - ./application:/app

networks:
  frontend:
  backend:
