parameters:
    kernel.secret: butitsnot
    kernel.root_dir: kernel.project_dir

framework:
    form: false
    assets: false
    session: false
    translator: false
    php_errors:
        log: true

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    service.default:
        class: App\Service\Main
        tags:
            - {name: controller.service_arguments}

    App\Interfaces\Endpoint:
        autowire: true
        factory: ['App\Factory\Endpoint', 'get']

    App\EventListener\Exception:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }